### PR TITLE
Improved data function last line matching

### PR DESCRIPTION
**Pull request by jrowen**
The original logic was causing problems if 'return' was present in any line, so this update should only remove the first line from the end that starts with 'return'.

### CODE REVIEW

**Comment by maxpumperla** [comment]
yep, you're right, thanks for this. Would you mind writing a little test for this? Would be great to have this covered.

**Comment by jrowen** [comment]
Sure, I'll try to pull something together shortly.

**Comment by maxpumperla** [comment]
Much appreciated, thank you!

**Comment by maxpumperla** [comment]
Again, many thanks for this, nicely spotted! Will merge now.

**Pull request merged**
