### PR TITLE
Resume parameter search from persistent trials

### PR DESCRIPTION
**Pull request by pkainz**
Motivated by the discussion on how to [resume the search in the hyperopt space from an existing trials database](https://github.com/hyperopt/hyperopt/issues/267), the current hyperas implementation must be adapted to support this transparently.

The current implementation of identifying the `best_run` to get the `model` from it actually modifies the mutable trials `dict` and unpacks the values from the `hyperopt` dictionary values (which are lists). 
Hence, when persisting the `trials` object outside the `hyperas.optim.minimize` function, it persists with unpacked values. When the `trials` object is loaded again in order to resume the training, `hyperopt` throws an error as it *again* tries to unpack the values from the trials object. This is actually connected to the `hyperopt.fmin` function argument `return_argmin`, which defaults to `True`. 
To add further transparency, this is now explicitly set to `True` in the corresponding function call within `hyperas.optim.base_minimizer`.

Example usage (inspired by [this comment](https://github.com/hyperopt/hyperopt/issues/267#issuecomment-272718758)):
```python
def run_trials():
    """
    Run a number of trials, save after a defined number of iterations.
    """
    trials_step = 1  # how many additional trials to do after loading saved trials. 1 = save after iteration
    max_evals = 5  # initial max_evals. put something small to not have to wait

    try:  
        trials = pickle.load(open('params.hyperopt', 'rb'))
        max_evals = len(trials.trials) + trials_step
        print('Continuing from {} trials to {} (+{}) trials'.format(len(trials.trials), max_evals, trials_step))
    except:
        trials = Trials()
        print('Starting new trials...')

    best, best_model = optim.minimize(
        model=model_fn,
        data=data_fn,
        algo=tpe.suggest,
        max_evals=max_evals,
        trials=trials, 
        eval_space=True
    )

    print("Best:", best)
    
    # save the trials object
    with open("params.hyperopt", "wb") as f:
        pickle.dump(trials, f)

# loop indefinitely and stop whenever you like
while True:
    run_trials()
```

### CODE REVIEW

**Comment by maxpumperla** [comment]
Makes sense, I was actually unaware of this behaviour. Thanks for this addition.

**Comment by jz314** [comment]
another thing I noticed: when using `tpe.suggest`, it is important to make initial `max_evals` > 20 because the first 20 evals by default are random, and it appears if you resume from saved trials while it is still in the random sampling phase it forgets how many it has sampled and starts the random sequence over.

**Comment by maxpumperla** [comment]
@jz314 yes, that's a rather unfortunate hyperopt convention. have you considered opening an issue against hyperopt? It'd be great to make this cold-start parameter configurable.

**Comment by jz314** [comment]
@maxpumperla in digging into the hyperopt code a bit it I found this helpful [snippet](https://github.com/hyperopt/hyperopt/blob/f38b538cfed9271e0fed5c5336eb8a45ae91d015/hyperopt/tests/test_pchoice.py#L121-L127). Basically add `from functools import partial` at the top, then substitute `algo=tpe.suggest` with `algo=partial(tpe.suggest, n_startup_jobs=<your_custom_number>)`

**Comment by maxpumperla** [comment]
that's a great finding, didn't know about this. :+1:

**Pull request merged**
