### PR TITLE
Python 3 support and Examples Update

### PR DESCRIPTION
**Pull request by MannyKayy**
I have added support for Python 3..

Tested using TF backend.

Not tested with Python 2.7

Fixed examples to work with latest keras.

Also had to pass a new argument  **nb_classes** to best ensemble in order to allow for the soft voting scheme

### CODE REVIEW

**Comment by maxpumperla** [comment]
That's pretty cool, thanks for this.

I'm now maintainer of hyperopt, so can probably release a new version of it that's python 3 compatible soon. In conjunction with this we should have python 3 support. Nice!

**Comment by maxpumperla** [comment]
Btw, I think travis is failing because keras now has tf as default backend, while this check runs with theano. So this should be fine. I should get around to test this tomorrow. 👍

**Comment by maccam912** [comment]
@MannyKayy You might be able to just update the travis.yml to install tensorflow. In https://github.com/maxpumperla/hyperas/blob/master/.travis.yml#L27 theano is added but never tensorflow which is what it is looking for.

**Comment by maxpumperla** [comment]
@MannyKayy thanks for this! Will fix CI later.

**Pull request merged**
