### PR TITLE
Enable hyper-parameter search space evaluation across trials

### PR DESCRIPTION
**Pull request by pkainz**
Issues #51 and #76 raise the feature request for a direct inspection of the selected search space. 

I have edited the `hyperas.optim.minimize` function to optionally return the bootstrapped `hyperopt` search space from the `base_minimizer` function as last return value, if an optional keyword argument `return_space` is set to `True`. This was previously not possible and `choice` filters contained the selected index instead of the value in the return value.

Additionally, the best results can directly be resolved to the actual parameter values by setting the new input argument `eval_space=True`.

The function call and return should be backwards compatible in order to prevent breaking the current API, hence the choice of new optional input arguments to steer the number of return values. 

Example for optimizer param search:
```python
from hyperopt import space_eval

def data():
    # ...

def model(...):
    # ...
    optimizer_ = SGD(
         lr={{uniform(1e-4, 1e-5)}},
         momentum={{choice([0.5, 0.9, 0.999])}},
         decay=0.0005,
         nesterov={{choice([True, False])}}
     )
    # ...

if __name__ == '__main__':
    trials=Trials()
    best_run, best_model, space = optim.minimize(
            model=model,
            data=data,
            algo=tpe.suggest,
            max_evals=2,
            trials=trials,
            eval_space=True,
            return_space=True
        )
    print(best_run)  # <-- now contains the values for 'lr', 'momentum', 'nesterov'
    
    # params for the different trials
    for t, trial in enumerate(trials):
        vals = trial.get('misc').get('vals')
        print("Trial %s vals: %s" % (t, vals))  # <-- indices
        print(space_eval(space, vals))  # <-- values 

```

### CODE REVIEW

**Comment by maxpumperla** [comment]
Thanks for this, also having backward compatibility in mind. Also, thank you for being active commenting on issues!

**Comment by caugusta** [comment]
I have downloaded the newest version of keras and hyperas and I am having the following issue with return_space:

      File "/.../temp_model.py", line 144, in keras_fmin_fnct
    NameError: global name 'filepath' is not defined

Here's my model definition and my main function:

    def model(x_train, y_train, x_test, y_test):
        model = Sequential()
        model.add(LSTM({{choice([10, 20, 50, 100])}}, input_shape=(x_train.shape[1],     x_train.shape[2]), return_sequences=False))
        model.add(Activation('relu'))
        if conditional({{choice(['one', 'two'])}}) == 'two':
            model.add(Dense(100))
            model.add({{choice([Dropout(0.5), Activation('linear')])}})
            model.add(Activation('relu'))

        model.add(Dense(8))
        model.add(Activation('softmax'))

        adam = keras.optimizers.Adam(lr={{choice([10**-6, 10**-5, 10**-4, 10**-3, 10**-2, 10**-1])}}, clipnorm=1.)
        rmsprop = keras.optimizers.RMSprop(lr={{choice([10**-6, 10**-5, 10**-4, 10**-3, 10**-2, 10**-1])}}, clipnorm=1.)
        sgd = keras.optimizers.SGD(lr={{choice([10**-6, 10**-5, 10**-4, 10**-3, 10**-2, 10**-1])}}, clipnorm=1.)

        choiceval = {{choice(['adam', 'sgd', 'rmsprop'])}}
        if choiceval == 'adam':
            optim = adam
        elif choiceval == 'rmsprop':
            optim = rmsprop
        else:
            optim = sgd
        model.compile(loss='categorical_crossentropy', metrics=['accuracy'],
                  optimizer=optim)

        earlyStopping = EarlyStopping(monitor='val_loss', min_delta=0, patience=20, verbose=0, mode='auto')
        checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
        callbacks_list = [earlyStopping, checkpoint]

        model.fit(x_train, y_train,
              batch_size={{choice([64, 128])}}, epochs=100,verbose=2,validation_data=(x_test, y_test), callbacks=callbacks_list)

        return {'loss': -acc, 'status': STATUS_OK, 'model': model}
    if __name__ == '__main__':
        tr_set = Trials()
        best_run, best_model, space = optim.minimize(model=model, data=data,algo=tpe.suggest,max_evals=100,trials=tr_set, return_space = True)
        X_train, Y_train, X_test, Y_test = data()
        for t, trial in enumerate(tr_set):
            vals = trial.get('misc').get('vals')
            print("Trial %s vals: %s" % (t, vals))
            print(space_eval(space, vals))
        print("Evalutation of best performing model:")
        print(best_model.evaluate(X_test, Y_test))
        print("Best performing model chosen hyper-parameters:")
        print(best_run)

**Comment by caugusta** [comment]
Has anyone else run into this error with space_eval? It seems to be hyperopt-related, but it might be a communication issue...

    Train on 5120 samples, validate on 1280 samples
    Epoch 1/1
    9s - loss: 2.0796 - acc: 0.1195 - val_loss: 2.0786 - val_acc: 0.1508
    Final validation accuracy: 0.15078125
    Train on 5120 samples, validate on 1280 samples
    Epoch 1/1
    16s - loss: 2.0798 - acc: 0.1234 - val_loss: 2.0795 - val_acc: 0.1250
    Final validation accuracy: 0.125
    Evalutation of best performing model:
    1280/1280 [==============================] - 3s     
    [2.0785847008228302, 0.15156249999999999]
    Best performing model chosen hyper-parameters:
    {'LSTM': 50, 'conditional': 'one', 'add': <keras.layers.core.Dropout object at 0xd988110>, 'batch_size': 128}
    Trial 0 vals: {'LSTM': [2], 'conditional': [0], 'add': [0], 'batch_size': [1]}
    Traceback (most recent call last):
    File "to_stack.py", line 93, in <module>
       print(space_eval(space, vals))
    File "/.../lib/python2.7/site-packages/hyperopt/fmin.py", line 342, in space_eval
    rval = pyll.rec_eval(space, memo=memo)
    File "/.../lib/python2.7/site-packages/hyperopt/pyll/base.py", line 870, in rec_eval
    raise TypeError('switch argument was', switch_i)
    TypeError: ('switch argument was', [0])

It runs no problem, and then chokes at the end with `space_eval`

Here are the `model()` and `__main__` functions:

    def model(x_train, y_train, x_test, y_test):
        model = Sequential()
        model.add(LSTM({{choice([10, 20, 50, 100])}}, input_shape=(x_train.shape[1], x_train.shape[2]), return_sequences=False))
        model.add(Activation('relu'))
        model.add(Dense(8))
        model.add(Activation('softmax'))

        model.compile(loss='categorical_crossentropy', metrics=['accuracy'],
                  optimizer='adam')

        model.fit(x_train, y_train,
              batch_size={{choice([64, 128])}}, epochs=1,verbose=2,validation_data=(x_test, y_test))
         score, acc = model.evaluate(x_test, y_test, verbose=0)
        print('Final validation accuracy:', acc)

        return {'loss': -acc, 'status': STATUS_OK, 'model': model}


    if __name__ == '__main__':
        trials=Trials()
        best_run, best_model, space = optim.minimize(model=model, data=data,algo=tpe.suggest,max_evals=2,trials=trials, eval_space=True, return_space=True)
        X_train, Y_train, X_test, Y_test = data()
        print("Evalutation of best performing model:")
        print(best_model.evaluate(X_test, Y_test))
        print("Best performing model chosen hyper-parameters:")
        print(best_run)
        for t, trial in enumerate(trials):
            vals = trial.get('misc').get('vals')
            print("Trial %s vals: %s" % (t, vals))
            print(space_eval(space, vals))

**Comment by maxpumperla** [comment]
@caugusta could you please open a ticket for this and also specify your exact dependencies and platform, so I can try to reproduce? thanks

**Comment by caugusta** [comment]
@maxpumperla Thank you, I have! Sorry for putting this in the wrong place.

**Comment by maxpumperla** [comment]
@caugusta don't worry, I was just afraid your request would get lost otherwise :)  no need to edit this.

**Comment by pkainz** [comment]
Issue #103 should be fixed by #104. 
To evaluate the `hyperopt` space, now use the new wrapper instead of the `hyperopt.space_eval`:
```python 
from hyperas.utils import eval_hyperopt_space
# ...
print(eval_hyperopt_space(space, vals))
```

**Comment by ncuxomun** [comment]
Hi, I have error saying that "line XX, i**n <module>
    return_space=True)
ValueError: too many values to unpack (expected 2)**", and i can't figure out what exactly the function is not returning. Can you please have a look at the snippet of my code below? 
Thank you!

    result = model.fit(X_train, y_train, batch_size={{choice([50, 100])}}, callbacks=[early_stop], epochs=EPOCHS, verbose=1, validation_data=(X_valid, y_valid))

    ## additional line
    loss, mse = model.evaluate(X_valid, y_valid, verbose=0)

    val_loss = np.amin(result.history['val_loss'])

    #get the lowest validation of the training epochs
    print('Best validation loss of epoch:', val_loss)

    return {'loss': val_loss, 'status': STATUS_OK, 'model': model}

#%%
if __name__ == '__main__':
    trials = Trials()
    best_run, best_model = optim.minimize(model=create_model,
                                          data=data,
                                          algo=tpe.suggest,
                                          max_evals=2,
                                          trials=trials,
                                          eval_space=True,
                                          return_space=True)

    X_train, Y_train, X_test, Y_test = data()
    print("Evalutation of best performing model:")
    print(best_model.evaluate(X_test, Y_test))
    print("Best performing model chosen hyper-parameters:")
    print(best_run)

    # params for the different trials
    for t, trial in enumerate(trials):
        vals = trial.get('misc').get('vals')
        print("Trial %s vals: %s" % (t, vals))  # <-- indices
        print(eval_hyperopt_space(space, vals))  # <-- values

**Pull request merged**
